axis_linear: 1 # Left thumb stick vertical
scale_linear: 0.2
scale_linear_turbo: 0.9

axis_angular: 2 # Left thumb stick horizontal
scale_angular: 0.3
scale_angular_turbo: 0.6

enable_button: 6 # Left trigger button
enable_turbo_button: 7 # Right trigger button
