port: "/dev/ttyS2"
baud: 115200

cmd_vel_timeout: 0.3

wheel_diameter: 0.15
wheel_separation: 0.5018

encoder_resolution: 37500

max_vel: 1.04
min_vel: 0.01

max_ampe: 100

time_check_motor_not_run: 10

use_encoder: true
motor_direction: false
motor_position_wrong: true
motor_mirror: false # Use when motor is mirror

keep_alive:
  topic: /moving_control/module_status
  timeout: -1.0
