port: "2-8.2.1"
baud: 115200

cmd_vel_timeout: 0.3

wheel_diameter: 0.15
wheel_separation: 0.505

encoder_resolution: 37500

max_vel: 1.04
min_vel: 0.01

max_ampe: 30

use_encoder: true
motor_direction: true

keep_alive:
  topic: /moving_control/module_status
  timeout: -1.0
